using UnityEngine;
using System;
using System.Collections.Generic;
using HedgehogTeam.EasyTouch;
using LuaInterface;
using BindType = ToLuaMenu.BindType;
using EnhancedUI.EnhancedScroller;


public static class CustomSettings
{
    public static string saveDir = Application.dataPath + "/Game/Scripts/Lua/LuaBind/";
    public static string toluaBaseType = Application.dataPath + "/ToLua/BaseType/";

    //导出时强制做为静态类的类型(注意customTypeList 还要添加这个类型才能导出)
    //unity 有些类作为sealed class, 其实完全等价于静态类
    public static List<Type> staticClassTypes = new List<Type>
    {        
        typeof(UnityEngine.Application),
        typeof(UnityEngine.Time),
        typeof(UnityEngine.Screen),
        typeof(UnityEngine.SleepTimeout),
        typeof(UnityEngine.Input),
        //typeof(UnityEngine.Resources),
        typeof(UnityEngine.Physics),
        typeof(UnityEngine.RenderSettings),
        typeof(UnityEngine.QualitySettings),
        typeof(UnityEngine.GL),
        typeof(UnityEngine.Graphics),
    };

    //附加导出委托类型(在导出委托时, customTypeList 中牵扯的委托类型都会导出， 无需写在这里)
    public static DelegateType[] customDelegateList = 
    {        
        _DT(typeof(Action)),                
        _DT(typeof(UnityEngine.Events.UnityAction)),
        _DT(typeof(System.Predicate<int>)),
        _DT(typeof(System.Action<int>)),
		_DT(typeof(System.Comparison<int>)),
		_DT(typeof(System.Func<int, int>)),

        _DT(typeof(System.Action<float>)),
        _DT(typeof(System.Action<string>)),
        _DT(typeof(System.Action<int, float, float>)),
        _DT(typeof(System.Action<string, UnityEngine.AnimatorStateInfo>)),
        _DT(typeof(System.Action<bool, string>)),


        _DT(typeof(DG.Tweening.TweenCallback)),
        _DT(typeof(NetClientExtensions.ReceiveMessageDelegate)),
        _DT(typeof(DG.Tweening.EaseFunction)),
    };

    //在这里添加你要导出注册到lua的类型列表
    public static BindType[] customTypeList = {
		//------------------------为例子导出--------------------------------
        //_GT(typeof(TestEventListener)),
        //_GT(typeof(TestProtol)),
        //_GT(typeof(TestAccount)),
        // _GT(typeof(UnityEngine.Resources)),
		//_GT(typeof(Dictionary<int, TestAccount>)).SetLibName("AccountMap"),
		//_GT(typeof(KeyValuePair<int, TestAccount>)),
        //_GT(typeof(Dictionary<int, TestAccount>.KeyCollection)),
		//_GT(typeof(Dictionary<int, TestAccount>.ValueCollection)),
		//_GT(typeof(TestExport)),
		//_GT(typeof(TestExport.Space)),
        //-------------------------------------------------------------------
		
		_GT(typeof(Debugger)).SetNameSpace(null),
        _GT(typeof(LogType)),
        _GT(typeof(UnityEngine.AssetBundleManifest)).AddExtendType(typeof(Nirvana.AssetBundleManifestExtension)),
        _GT(typeof(UnityEngine.RectTransform)).AddExtendType(typeof(DG.Tweening.ShortcutExtensions46)).AddExtendType(typeof(Nirvana.RectTransformExtensions)),
        _GT(typeof(UnityEngine.RectTransform.Edge)),
        _GT(typeof(UnityEngine.Canvas)),
        _GT(typeof(UnityEngine.TextAnchor)),
        _GT(typeof(UnityEngine.CanvasGroup)).AddExtendType(typeof(CanvasGroupExtensions)),
        _GT(typeof(Projectile)),
        _GT(typeof(ProjectileSingle)),
        _GT(typeof(UnityEngine.RectOffset)),
        _GT(typeof(UnityEngine.UI.GridLayoutGroup)),
        _GT(typeof(UnityEngine.UI.VerticalLayoutGroup)),
        _GT(typeof(UnityEngine.UI.HorizontalLayoutGroup)),
        _GT(typeof(UnityEngine.Events.UnityEventBase)),
        _GT(typeof(UnityEngine.Events.UnityEvent)),
        _GT(typeof(UnityEngine.EventSystems.UIBehaviour)),
        _GT(typeof(UnityEngine.EventSystems.AbstractEventData)),
        _GT(typeof(UnityEngine.EventSystems.EventTrigger)),
        _GT(typeof(UnityEngine.UI.Selectable)),
        _GT(typeof(UnityEngine.UI.Selectable.Transition)),
        _GT(typeof(UnityEngine.UI.Graphic)),
        _GT(typeof(UnityEngine.UI.MaskableGraphic)),
        _GT(typeof(UnityEngine.UI.Button)).AddExtendType(typeof(ButtonExtensions)),
        _GT(typeof(UnityEngine.UI.Button.ButtonClickedEvent)),
        _GT(typeof(UnityEngine.UI.Toggle)).AddExtendType(typeof(ToggleExtensions)),
        _GT(typeof(UnityEngine.UI.Toggle.ToggleEvent)),
        _GT(typeof(UnityEngine.UI.ToggleGroup)),
        _GT(typeof(UnityEngine.UI.Text)).AddExtendType(typeof(TestExtensions)),
        _GT(typeof(UnityEngine.UI.Image)).AddExtendType(typeof(DG.Tweening.ShortcutExtensions46)),
        _GT(typeof(UnityEngine.UI.Image.Type)),
        _GT(typeof(UnityEngine.UI.RawImage)),
        _GT(typeof(UnityEngine.UI.Outline)),
        _GT(typeof(UnityEngine.UI.ScrollRect)),
        _GT(typeof(ListenTrigger)),
        _GT(typeof(UnityEngine.UI.ScrollRect.ScrollRectEvent)),
        _GT(typeof(UnityEngine.UI.InputField)).AddExtendType(typeof(InputFieldExtensions)),
        _GT(typeof(UnityEngine.UI.InputField.SubmitEvent)),
        _GT(typeof(UnityEngine.UI.InputField.OnChangeEvent)),
        _GT(typeof(UnityEngine.UI.Dropdown)),
        _GT(typeof(UnityEngine.UI.Dropdown.OptionData)),
        _GT(typeof(UnityEngine.UI.Dropdown.DropdownEvent)),
        _GT(typeof(UnityEngine.UI.Slider)).AddExtendType(typeof(SliderExtensions)).AddExtendType(typeof(DG.Tweening.ShortcutExtensions46)),
        _GT(typeof(UnityEngine.UI.Slider.SliderEvent)),
        _GT(typeof(UnityEngine.UI.LayoutRebuilder)),
        _GT(typeof(UnityEngine.UI.LayoutElement)),
        _GT(typeof(UnityEngine.UI.Shadow)),
        _GT(typeof(UnityEngine.UI.BaseMeshEffect)),
        _GT(typeof(UnityEngine.ScriptableObject)),
        _GT(typeof(UnityEngine.Rect)),
        _GT(typeof(UnityEngine.RaycastHit)),
        _GT(typeof(UnityEngine.AnimatorStateInfo)),
        _GT(typeof(UnityEngine.RuntimePlatform)),
        _GT(typeof(UnityEngine.RectTransformUtility)),
        _GT(typeof(UnityEngine.EventSystems.PointerEventData)),
        _GT(typeof(UnityEngine.EventSystems.BaseEventData)),
        _GT(typeof(UnityEngine.EventSystems.AxisEventData)),
        _GT(typeof(UnityEngine.SceneManagement.SceneManager)),
        _GT(typeof(UnityEngine.SceneManagement.LoadSceneMode)),
        _GT(typeof(UnityEngine.SceneManagement.Scene)),
        _GT(typeof(UnityEngine.ShaderVariantCollection)),
        _GT(typeof(UnityEngine.Debug)),
        _GT(typeof(UnityEngine.PrimitiveType)),
        _GT(typeof(UnityEngine.PlayerPrefs)),
        _GT(typeof(UnityEngine.SystemInfo)),
        _GT(typeof(UnityEngine.Audio.AudioMixer)),
        _GT(typeof(UnityEngine.Profiling.Profiler)),
        _GT(typeof(UnityEngine.Playables.PlayableDirector)),
        _GT(typeof(UnityEngine.Playables.PlayState)),
        _GT(typeof(UnityEngine.Networking.UnityWebRequest)).AddExtendType(typeof(WebRequestExteions)),
        _GT(typeof(UnityEngine.Networking.DownloadHandler)),
        _GT(typeof(UnityEngine.Networking.DownloadHandlerAssetBundle)),
        _GT(typeof(UnityEngine.Networking.UnityWebRequestAsyncOperation)),
        _GT(typeof(UnityEngine.AssetBundle)),
        _GT(typeof(UnityEngine.TextAsset)),
        _GT(typeof(EditorResourceMgr)),
        _GT(typeof(UnityEngine.StaticBatchingUtility)),
        _GT(typeof(UnityEngine.TextMesh)),
        _GT(typeof(UnityEngine.iOS.Device)),
        _GT(typeof(UnityEngine.iOS.DeviceGeneration)),
        _GT(typeof(UnityEngine.AssetBundleCreateRequest)),
        _GT(typeof(UnityEngine.AssetBundleRequest)),
        _GT(typeof(UnityEngine.Rendering.ShadowCastingMode)),
        _GT(typeof(UtilU3d)),
        _GT(typeof(MoveableObject)),
        _GT(typeof(LockRotation)),
        _GT(typeof(CameraFollow)),
        _GT(typeof(ClickManager)),
        _GT(typeof(ClickableObject)),
        _GT(typeof(ActorController)),
        _GT(typeof(ActorAttachment)),
        _GT(typeof(AttachObject)),
        _GT(typeof(FollowTarget)),
        _GT(typeof(CGController)),
		_GT(typeof(CharacterGhost)),
        _GT(typeof(Fazhen)),
        _GT(typeof(MaterialSwitcher)),
        _GT(typeof(UIJoystick)),
        _GT(typeof(UIJoystick.JoystickMode)),
        _GT(typeof(FPSSampler)),
        _GT(typeof(ActorFadeout)),
        _GT(typeof(ActorAttachEffect)),
        _GT(typeof(UIPrefabLoader)),
        _GT(typeof(GameLayers)),
        _GT(typeof(QualityBudget)),
        //_GT(typeof(IosAudit)),
        _GT(typeof(CameraShake)),
        _GT(typeof(ZipUtils)),
		_GT(typeof(OcclusionObject)),
		_GT(typeof(OcclusionObject.OcclusionItme)),
        _GT(typeof(LuaUInt64)),
        _GT(typeof(TrailRendererController)),
        _GT(typeof(OverrideOrderGroupMgr)),
        _GT(typeof(SceneOptimizeMgr)),
        _GT(typeof(FontTextureReBuild)),
        _GT(typeof(QingGongState)),
        _GT(typeof(ActorQingGongObject)),
        _GT(typeof(UIEffect)),
        _GT(typeof(EffectOrderGroup)),
        _GT(typeof(ShowFPS)),
        _GT(typeof(ActorRender)),
        //_GT(typeof(IosAuditMgr)), --ylsp
        
        // _GT(typeof(Nirvana.AudioManager)).SetNameSpace(null),
        _GT(typeof(Nirvana.AssetID)).SetNameSpace(null),
        _GT(typeof(Nirvana.I18N)).SetNameSpace(null),
        _GT(typeof(Nirvana.Scheduler)).SetNameSpace(null),
        _GT(typeof(Nirvana.UINameTable)).SetNameSpace(null),
        // _GT(typeof(Nirvana.UIEventTable)).SetNameSpace(null),
        _GT(typeof(Nirvana.SignalHandle)).SetNameSpace(null),
        // _GT(typeof(Nirvana.UIVariableTable)).SetNameSpace(null),
        // _GT(typeof(Nirvana.UIVariable)).SetNameSpace(null),
        _GT(typeof(Nirvana.AccordionElement)).SetNameSpace(null),
        _GT(typeof(Nirvana.UI3DDisplay)).SetNameSpace(null),
        _GT(typeof(Nirvana.UIFollowTarget)).SetNameSpace(null),
        // _GT(typeof(Nirvana.AssetManager)).SetNameSpace(null),
        _GT(typeof(Nirvana.AssetBundleFileInfo)).SetNameSpace(null),
        _GT(typeof(Nirvana.EventTriggerListener)).AddExtendType(typeof(EventTriggerListenerExtensions)).SetNameSpace(null),
        _GT(typeof(Nirvana.ToggleClickHandler)),
        _GT(typeof(Nirvana.UIGrayscale)).SetNameSpace(null),
        _GT(typeof(Nirvana.UIGradient)).SetNameSpace(null),
        _GT(typeof(Nirvana.MinimapCamera)).SetNameSpace(null),
        _GT(typeof(Nirvana.SortingOrderOverrider)).SetNameSpace(null),
        _GT(typeof(Nirvana.RichTextGroup)).SetNameSpace(null),
        _GT(typeof(Nirvana.ButtonEx)).SetNameSpace(null),
        _GT(typeof(Nirvana.GridView)).SetNameSpace(null),
        _GT(typeof(Nirvana.CircleRawImage)).SetNameSpace(null),
        // _GT(typeof(Nirvana.ScriptablePool)).SetNameSpace(null),

        _GT(typeof(Nirvana.AudioItem)).SetNameSpace(null),
        _GT(typeof(Nirvana.AudioDummyController)).SetNameSpace(null),
        _GT(typeof(Nirvana.AudioSingleController)).SetNameSpace(null),
        _GT(typeof(Nirvana.AudioSequenceController)).SetNameSpace(null),
        _GT(typeof(Nirvana.AudioSourcePool)).SetNameSpace(null),

        _GT(typeof(UiParticles.UiParticles)),
        _GT(typeof(Nirvana.EffectControl)).SetNameSpace(null),
        _GT(typeof(Nirvana.DeviceTool)).SetNameSpace(null),
        _GT(typeof(Nirvana.WebView)).SetNameSpace(null),
        _GT(typeof(Nirvana.AudioRecorder)).SetNameSpace(null),
        _GT(typeof(Nirvana.AudioGVoice)).SetNameSpace(null),
        _GT(typeof(Nirvana.AudioPlayer)).SetNameSpace(null),
        _GT(typeof(Nirvana.ImagePicker)).SetNameSpace(null),
        _GT(typeof(Nirvana.NetClient)).SetNameSpace(null).AddExtendType(typeof(NetClientExtensions)),
        _GT(typeof(Nirvana.ListView)),
        _GT(typeof(Nirvana.PageView)).SetNameSpace(null),
        _GT(typeof(Nirvana.QualityConfig)).SetNameSpace(null),
        _GT(typeof(Nirvana.QualityControlActive)).SetNameSpace(null),
        _GT(typeof(Nirvana.ChannelAgent)).SetNameSpace(null),
        _GT(typeof(Nirvana.ChannelUserInfo)).SetNameSpace(null),
        _GT(typeof(Nirvana.DialogManager)).SetNameSpace(null),
        _GT(typeof(Nirvana.LocalNotification)).SetNameSpace(null),
        _GT(typeof(Nirvana.LocalNotification.CalendarUnit)).SetNameSpace(null),
        _GT(typeof(Nirvana.SimpleShadow)).SetNameSpace(null),
		_GT(typeof(Nirvana.NirvanaRenderer)).SetNameSpace(null),
        _GT(typeof(Nirvana.UIBlock)),
        _GT(typeof(Game.AttachSkin)).SetNameSpace(null),
        _GT(typeof(Game.AttachSkinObject)).SetNameSpace(null),
        // _GT(typeof(Nirvana.MaterialPool)).SetNameSpace(null),
        // _GT(typeof(Nirvana.LoadRawImage)),
        _GT(typeof(Nirvana.LoadRawImageURL)),
        // _GT(typeof(Nirvana.GameObjectAttach)),
        _GT(typeof(Nirvana.StreamingAssets)).SetNameSpace(null),
        _GT(typeof(PostEffects)),
        _GT(typeof(MD5)),
        _GT(typeof(MD52)),
        _GT(typeof(StringUtil)),
        _GT(typeof(UIDrag)),
        _GT(typeof(CurveMove)),
        _GT(typeof(ListViewDelegate)),
        _GT(typeof(ListViewCell)),
        _GT(typeof(ListViewPageScroll)),
        _GT(typeof(ListViewPageScroll2)),
        _GT(typeof(EnhancedScroller)),
        _GT(typeof(EnhancedScrollerCellView)),
        _GT(typeof(ListViewSimpleDelegate)),
        _GT(typeof(PageViewSimpleDelegate)),
        _GT(typeof(GameRoot)),
        _GT(typeof(GridFindWay)),
        _GT(typeof(GridCellType)),
        _GT(typeof(EasyTouch)).SetNameSpace(null),
        _GT(typeof(HedgehogTeam.EasyTouch.BaseFinger)),
        _GT(typeof(EasyTouch.SwipeDirection)).SetNameSpace("EasyTouch"),
        _GT(typeof(Gesture)).SetNameSpace(null),
        _GT(typeof(UIFollowDistance)),
        _GT(typeof(SafeAreaAdpater)),
        _GT(typeof(CameraCullingDistance)),
        //_GT(typeof(EncryptMgr)), --ylsp
        
//#if USING_DOTWEENING
        _GT(typeof(DG.Tweening.DOTween)),
        _GT(typeof(DG.Tweening.Tween)).SetBaseType(typeof(System.Object)).AddExtendType(typeof(DG.Tweening.TweenExtensions)),
        _GT(typeof(DG.Tweening.Sequence)).AddExtendType(typeof(DG.Tweening.TweenSettingsExtensions)),
        _GT(typeof(DG.Tweening.Tweener)).AddExtendType(typeof(DG.Tweening.TweenSettingsExtensions)),
        _GT(typeof(DG.Tweening.LoopType)),
        _GT(typeof(DG.Tweening.PathMode)),
        _GT(typeof(DG.Tweening.PathType)),
        _GT(typeof(DG.Tweening.RotateMode)),
        _GT(typeof(DG.Tweening.Ease)),
        _GT(typeof(DG.Tweening.Core.TweenerCore<float,float,DG.Tweening.Plugins.Options.FloatOptions>)),
        _GT(typeof(Component)).AddExtendType(typeof(Nirvana.ComponentExtensions)).AddExtendType(typeof(DG.Tweening.ShortcutExtensions)),
        _GT(typeof(Transform)).AddExtendType(typeof(Nirvana.TransformExtensions)).AddExtendType(typeof(DG.Tweening.ShortcutExtensions)),
        _GT(typeof(Light)).AddExtendType(typeof(DG.Tweening.ShortcutExtensions)),
        _GT(typeof(Material)).AddExtendType(typeof(DG.Tweening.ShortcutExtensions)),
        _GT(typeof(Rigidbody)).AddExtendType(typeof(DG.Tweening.ShortcutExtensions)),
        _GT(typeof(Camera)).AddExtendType(typeof(DG.Tweening.ShortcutExtensions)),
        _GT(typeof(AudioSource)).AddExtendType(typeof(DG.Tweening.ShortcutExtensions)),
        _GT(typeof(LineRenderer)).AddExtendType(typeof(DG.Tweening.ShortcutExtensions)),
        _GT(typeof(Game.GameObjectAttach)),
        _GT(typeof(Game.LoadRawImage)),
        //_GT(typeof(TrailRenderer)).AddExtendType(typeof(DG.Tweening.ShortcutExtensions)),
//#else
//        _GT(typeof(Component)),
//		_GT(typeof(Transform)).AddExtendType(typeof(TransformEx)),
//		_GT(typeof(Material)),
//		_GT(typeof(Light)),
//		_GT(typeof(Rigidbody)),
//		_GT(typeof(Camera)),
//		_GT(typeof(AudioSource)),
        //_GT(typeof(LineRenderer))
        //_GT(typeof(TrailRenderer))
//#endif

        _GT(typeof(Behaviour)),
        _GT(typeof(MonoBehaviour)),
        _GT(typeof(GameObject)).AddExtendType(typeof(Nirvana.GameObjectExtensions)),
        _GT(typeof(TrackedReference)),
        _GT(typeof(Application)),
        _GT(typeof(ThreadPriority)),
        _GT(typeof(Physics)),
        _GT(typeof(Collider)),
        _GT(typeof(Time)),
        _GT(typeof(Texture)),
        _GT(typeof(Texture2D)),
        _GT(typeof(Shader)),
        _GT(typeof(Renderer)),
        _GT(typeof(WWW)),
        _GT(typeof(Screen)),
        _GT(typeof(CameraClearFlags)),
        _GT(typeof(AudioClip)),
        //_GT(typeof(AssetBundle)),
        _GT(typeof(ParticleSystem)),
        _GT(typeof(AsyncOperation)).SetBaseType(typeof(System.Object)),
        _GT(typeof(LightType)),
        _GT(typeof(SleepTimeout)),
        _GT(typeof(TrailRenderer)),
        _GT(typeof(ScreenCapture)),
#if UNITY_5_3_OR_NEWER && !UNITY_5_6_OR_NEWER
        _GT(typeof(UnityEngine.Experimental.Director.DirectorPlayer)),
#endif
        _GT(typeof(Animator)).AddExtendType(typeof(Nirvana.AnimatorExtensions)),
        _GT(typeof(Input)),
        _GT(typeof(KeyCode)),
        _GT(typeof(SkinnedMeshRenderer)),
        _GT(typeof(Space)),

        _GT(typeof(MeshRenderer)),
#if !UNITY_5_4_OR_NEWER
        _GT(typeof(ParticleEmitter)),
        _GT(typeof(ParticleRenderer)),
        _GT(typeof(ParticleAnimator)), 
#endif

        _GT(typeof(BoxCollider)),
        _GT(typeof(MeshCollider)),
        _GT(typeof(SphereCollider)),
        _GT(typeof(CharacterController)),
        _GT(typeof(CapsuleCollider)),

        _GT(typeof(Animation)),
        _GT(typeof(AnimationClip)).SetBaseType(typeof(UnityEngine.Object)),
        _GT(typeof(AnimationState)),
        _GT(typeof(AnimationBlendMode)),
        _GT(typeof(QueueMode)),
        _GT(typeof(PlayMode)),
        _GT(typeof(WrapMode)),
        _GT(typeof(AnimatorCullingMode)),

        _GT(typeof(QualitySettings)),
        _GT(typeof(RenderSettings)),
        _GT(typeof(BlendWeights)),
        _GT(typeof(RenderTexture)),
        _GT(typeof(Resources)),        
        _GT(typeof(System.IO.File)),
        _GT(typeof(System.IO.Directory)),
        _GT(typeof(System.IO.SearchOption)),
        _GT(typeof(System.IO.Path)),
        _GT(typeof(RuntimeAssetHelper)),
        _GT(typeof(Uri)),
        _GT(typeof(UnityEngine.Sprite)),
    };

    public static List<Type> dynamicList = new List<Type>() {
        typeof(MeshRenderer),
#if !UNITY_5_4_OR_NEWER
        typeof(ParticleEmitter),
        typeof(ParticleRenderer),
        typeof(ParticleAnimator),
#endif

        typeof(BoxCollider),
        typeof(MeshCollider),
        typeof(SphereCollider),
        typeof(CharacterController),
        typeof(CapsuleCollider),

        typeof(Animation),
        typeof(AnimationClip),
        typeof(AnimationState),

        typeof(BlendWeights),
        typeof(RenderTexture),
        typeof(Rigidbody),
    };

    //重载函数，相同参数个数，相同位置out参数匹配出问题时, 需要强制匹配解决
    //使用方法参见例子14
    public static List<Type> outList = new List<Type>()
    {
        
    };
        
    //ngui优化，下面的类没有派生类，可以作为sealed class
    public static List<Type> sealedList = new List<Type>()
    {
        /*typeof(Transform),
        typeof(UIRoot),
        typeof(UICamera),
        typeof(UIViewport),
        typeof(UIPanel),
        typeof(UILabel),
        typeof(UIAnchor),
        typeof(UIAtlas),
        typeof(UIFont),
        typeof(UITexture),
        typeof(UISprite),
        typeof(UIGrid),
        typeof(UITable),
        typeof(UIWrapGrid),
        typeof(UIInput),
        typeof(UIScrollView),
        typeof(UIEventListener),
        typeof(UIScrollBar),
        typeof(UICenterOnChild),
        typeof(UIScrollView),        
        typeof(UIButton),
        typeof(UITextList),
        typeof(UIPlayTween),
        typeof(UIDragScrollView),
        typeof(UISpriteAnimation),
        typeof(UIWrapContent),
        typeof(TweenWidth),
        typeof(TweenAlpha),
        typeof(TweenColor),
        typeof(TweenRotation),
        typeof(TweenPosition),
        typeof(TweenScale),
        typeof(TweenHeight),
        typeof(TypewriterEffect),
        typeof(UIToggle),
        typeof(Localization),*/
    };

    public static BindType _GT(Type t)
    {
        return new BindType(t);
    }

    public static DelegateType _DT(Type t)
    {
        return new DelegateType(t);
    }    
}
